# Generated by Django 5.0.2 on 2024-03-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_item_price_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
