# Generated by Django 5.0.2 on 2024-03-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_recentlyviewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentlyViewed',
        ),
    ]
